In [4]:
import math

# Translation data for "frame" and "crazy_2"
frame_translation = {
    "x": -0.37908925595768617,
    "y": 1.4585831693767384,
    "z": 0.6731063200291997,
}

crazy_2_translation = {
    "x": -0.3975092252436137,
    "y": 0.3107741593833483,
    "z": -0.006229286471791172,
}
# desired - frame = drone
# -0.2,-1.38800003,0.0

distance_x = (crazy_2_translation["x"] - frame_translation["x"])

distance_y = (crazy_2_translation["y"] - frame_translation["y"]) 
distance_z = (crazy_2_translation["z"] - frame_translation["z"]) 

print("Distance between 'frame' and 'crazy_2':", distance_x, distance_y, distance_z, "meters")


Distance between 'frame' and 'crazy_2': -0.01841996928592754 -1.1478090099933902 -0.6793356065009909 meters


In [9]:

# Define the target z position for climbing
target_z_climb = 0.44

# Calculate the intermediate waypoint for climbing
climb_waypoint = {
    "x": crazy_2_translation["x"],
    "y": crazy_2_translation["y"],
    "z": target_z_climb,
}

# Define the target frame location
frame_translation = {
    "x": -0.37908925595768617,
    "y": 1.4585831693767384,
    "z": 0.44,  # The target height you want to maintain during forward motion
}

# Calculate the final waypoint for moving forward
forward_waypoint = {
    "x": frame_translation["x"],
    "y": frame_translation["y"],
    "z": target_z_climb,  # Maintain the target height while moving forward
}

# Define the number of intermediate waypoints
num_intermediate_waypoints = 10

# Create a list of waypoints for the entire trajectory
waypoints = []

# Add intermediate waypoints for climbing
for i in range(num_intermediate_waypoints):
    alpha = i / (num_intermediate_waypoints - 1)
    intermediate_point = {
        "x": crazy_2_translation["x"],
        "y": crazy_2_translation["y"],
        "z": (1 - alpha) * crazy_2_translation["z"] + alpha * target_z_climb,
    }
    waypoints.append(intermediate_point)

# Add the forward waypoint
waypoints.append(forward_waypoint)


In [11]:
# Define the number of intermediate waypoints
num_intermediate_waypoints = 10

# Create a list of waypoints for the entire trajectory
waypoints = []

# Add intermediate waypoints for climbing
for i in range(num_intermediate_waypoints):
    alpha = i / (num_intermediate_waypoints - 1)
    intermediate_point = {
        "x": crazy_2_translation["x"],
        "y": crazy_2_translation["y"],
        "z": (1 - alpha) * crazy_2_translation["z"] + alpha * target_z_climb,
    }
    waypoints.append(intermediate_point)

# Add the forward waypoint
waypoints.append(forward_waypoint)
print (waypoints)

[{'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': -0.006229286471791172}, {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.04335174535840784}, {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.09293277718860686}, {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.1425138090188059}, {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.19209484084900488}, {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.24167587267920396}, {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.29125690450940295}, {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.34083793633960197}, {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.39041896816980093}, {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.44}, {'x': -0.37908925595768617, 'y': 1.4585831693767384, 'z': 0.44}]


In [13]:
import numpy as np

# Define the list of dictionaries
data = [
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': -0.006229286471791172},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.04335174535840784},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.09293277718860686},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.1425138090188059},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.19209484084900488},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.24167587267920396},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.29125690450940295},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.34083793633960197},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.39041896816980093},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.44},
    {'x': -0.37908925595768617, 'y': 1.4585831693767384, 'z': 0.44}
]

# Extract x, y, and z values into separate arrays
x_values = [item['x'] for item in data]
y_values = [item['y'] for item in data]
z_values = [item['z'] for item in data]

# Create a 10 by 3 matrix
matrix = np.column_stack((x_values, y_values, z_values))

# Print the resulting matrix
print(matrix)
data = [
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': -0.006229286471791172},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.04335174535840784},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.09293277718860686},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.1425138090188059},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.19209484084900488},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.24167587267920396},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.29125690450940295},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.34083793633960197},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.39041896816980093},
    {'x': -0.3975092252436137, 'y': 0.3107741593833483, 'z': 0.44},
    {'x': -0.37908925595768617, 'y': 1.4585831693767384, 'z': 0.44}
]

# Extract x, y, and z values into separate arrays
x_values = [item['x'] for item in data]
y_values = [item['y'] for item in data]
z_values = [item['z'] for item in data]

# Create a 10 by 3 matrix
matrix = np.column_stack((x_values, y_values, z_values))

# Print the resulting matrix without the outer brackets
for row in matrix:
    print(row)



[[-0.39750923  0.31077416 -0.00622929]
 [-0.39750923  0.31077416  0.04335175]
 [-0.39750923  0.31077416  0.09293278]
 [-0.39750923  0.31077416  0.14251381]
 [-0.39750923  0.31077416  0.19209484]
 [-0.39750923  0.31077416  0.24167587]
 [-0.39750923  0.31077416  0.2912569 ]
 [-0.39750923  0.31077416  0.34083794]
 [-0.39750923  0.31077416  0.39041897]
 [-0.39750923  0.31077416  0.44      ]
 [-0.37908926  1.45858317  0.44      ]]
[-0.39750923  0.31077416 -0.00622929]
[-0.39750923  0.31077416  0.04335175]
[-0.39750923  0.31077416  0.09293278]
[-0.39750923  0.31077416  0.14251381]
[-0.39750923  0.31077416  0.19209484]
[-0.39750923  0.31077416  0.24167587]
[-0.39750923  0.31077416  0.2912569 ]
[-0.39750923  0.31077416  0.34083794]
[-0.39750923  0.31077416  0.39041897]
[-0.39750923  0.31077416  0.44      ]
[-0.37908926  1.45858317  0.44      ]
